site_name: mkdocs-apidescribed
site_url: !ENV READTHEDOCS_CANONICAL_URL

copyright: Copyright &copy; 2025, Igor Starikov

repo_url: https://github.com/idlesign/mkdocs-apidescribed-plugin
edit_uri: edit/master/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/idlesign

plugins:
  - search
  - apidescribed

theme:
  name: material
  palette:
    primary: green
  features:
    - navigation.top
    - toc.follow
    - content.action.view
    - content.action.edit
    - content.code.copy

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
